/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mycode.dbconnect;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Acer
 */
public class add extends javax.swing.JPanel {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    /**
     * Creates new form add
     */
    public add() {
        initComponents();
        jPanel1.setBackground(new Color(255,255,255,180));
        con =dbconnect.connect();
        tableload();
        jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        jTable1.getTableHeader().setOpaque(false);
       
        jTable1.getTableHeader().setBackground(new Color(255,51,51));
        jTable1.getTableHeader().setForeground( Color.BLACK);
        jTable1.setRowHeight(25);
            
    }
    public void tableload()
    {
       try{
      
         String sql = "SELECT  add_id  as 'Bar code', product_name as 'Description' ,u_price as 'Unit Price' , box as 'No Of Boxes', box_pac as 'No Of Packet In The Box' , pac as 'Loose Packet' ,tot_pac as 'Total Packet' FROM add1" ;
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
               
       }catch(Exception e){
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uid = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        no_box = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        los_pac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        packet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        pname1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        add_no_box = new javax.swing.JTextField();
        add_packet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uid.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        uid.setText("0");
        add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 230, 25));

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/ok_100483.jpg"))); // NOI18N
        jButton3.setText("add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 110, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 40, 40));

        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/update.jpg"))); // NOI18N
        jButton4.setText("update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 130, 40));

        jButton5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel_100824.jpg"))); // NOI18N
        jButton5.setText("delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 120, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setText("No of box         :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 25));

        jTextField4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 330, 25));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setText("unit price         :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 25));

        price.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 270, 25));

        no_box.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jPanel1.add(no_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 120, 25));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel10.setText("no of packet");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 25));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel9.setText("in the box        :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 25));

        los_pac.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jPanel1.add(los_pac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 270, 25));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setText("loose packet    :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, 25));

        packet.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jPanel1.add(packet, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 120, 25));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel5.setText("id  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, 25));

        jTable1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 910, 560));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setText("product Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 25));

        pname1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jPanel1.add(pname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 270, 25));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/addnew.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 25, 25));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/addnew.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 25, 25));

        add_no_box.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        add_no_box.setText("0");
        jPanel1.add(add_no_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 100, 25));

        add_packet.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        add_packet.setText("0");
        jPanel1.add(add_packet, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 100, 25));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/add.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String name = pname1.getText();
       // String price =uprice.getText();
     //String qty = sqty.getText();
        Double price2=Double.valueOf(price.getText());
        String bprice=String.format("%.2f", price2);
        
        int box2=Integer.parseInt(no_box.getText());
      int add_box1=Integer.parseInt(add_no_box.getText());
      int box1;
      box1=box2+add_box1;
        
        int in_box=Integer.parseInt(los_pac.getText());
       int pack1=Integer.parseInt(packet.getText());
        int add_pack=Integer.parseInt(add_packet.getText()); 
        int pack;
        pack=pack1+add_pack;
        int tot;
        tot=(box1*in_box)+pack;
       
        
        try{
        
       String q= "INSERT INTO add1(product_name,u_price,box,box_pac,pac,tot_pac) values ('"+name+"' ,'"+bprice+"' , '"+box1+"' , '"+in_box+"'  , '"+pack+"' ,'"+tot+"' )"; 
       pst = con.prepareStatement(q);
       pst.execute();
       
       tableload();
        }
        catch(Exception e){
          System.out.println(e);
          
      }
        pname1.setText(" ");
        price.setText("  ");
        no_box.setText("  ");
        los_pac.setText("  ");
        packet.setText("   ");
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        String uit = jTable1.getValueAt(r, 0).toString();
        String name = jTable1.getValueAt(r, 1).toString();
        String sprice = jTable1.getValueAt(r, 2).toString();
        String bprice = jTable1.getValueAt(r, 3).toString();
        String price1 = jTable1.getValueAt(r, 4).toString();
        String qty = jTable1.getValueAt(r, 5).toString();
        uid.setText(uit);
        pname1.setText(name);
        price.setText(sprice);
        no_box.setText(bprice);
        los_pac.setText(price1);
        packet.setText(qty);         
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         int x = JOptionPane.showConfirmDialog(null, "Do You Really Want To Update");
        if(x==0)
    {
      
      int id=Integer.parseInt(uid.getText());
      String name = pname1.getText();
      Double price2=Double.valueOf(price.getText());
        String bprice=String.format("%.2f", price2);
      int box2=Integer.parseInt(no_box.getText());
      int add_box1=Integer.parseInt(add_no_box.getText());
      int box1;
     box1=box2+add_box1;
        int in_box=Integer.parseInt(los_pac.getText());
        
        int pack1=Integer.parseInt(packet.getText());
        int add_pack=Integer.parseInt(add_packet.getText()); 
        int pack;
        pack=pack1+add_pack;
        
        
        int tot;
        tot=(box1*in_box)+pack;
        int box11,pack11;
        
        box11=tot/in_box;
        pack11=tot%in_box;
        
      
      String sql = " UPDATE add1 SET product_name = '"+ name +"' ,u_price = '"+bprice+"' ,box = '"+ box11 +"' , box_pac = '"+in_box+"'  ,pac = '"+ pack11 +"' , tot_pac = '"+tot+"'  where add_id  = '"+id+"' ";   
        try{
            
         pst = con.prepareStatement(sql);
         pst.execute(); 
         
         tableload();
            
        }catch(Exception e){
    }                                        
    }
        pname1.setText("  ");
        price.setText("  ");
        no_box.setText("  ");
        los_pac.setText("  ");
        packet.setText("   ");  
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null,"Do You Really Want To Delete");
        if(x==0)
        {
        
        int id=Integer.parseInt(uid.getText());
        
        String sql = "DELETE from add1 where add_id='"+id+"' ";
        try {
        
         pst = con.prepareStatement(sql);
         pst.execute();
            
           tableload(); 
        }
          catch(Exception e){ 
    }}
        
        pname1.setText("  ");
        price.setText("  ");
        no_box.setText("  ");
        los_pac.setText("  ");
        packet.setText("   "); 
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = pname1.getText();
         
        String sql = "Select add_id, product_name,u_price, box, box_pac,pac,tot_pac from add1 where product_name LIKE '%"+ name +"%'";
        try{
        
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_no_box;
    private javax.swing.JTextField add_packet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField los_pac;
    private javax.swing.JTextField no_box;
    private javax.swing.JTextField packet;
    private javax.swing.JTextField pname1;
    private javax.swing.JTextField price;
    private javax.swing.JLabel uid;
    // End of variables declaration//GEN-END:variables
}
