/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import MainStuffs.JpanelLoader;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import mycode.dbconnect;

/**
 *
 * @author Acer
 */
public class admin1 extends javax.swing.JFrame {

    JpanelLoader jploade = new JpanelLoader();

    /**
     * Creates new form admin1
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    Statement stmt;
    public admin1() {
        initComponents();
        jPanel1.setBackground(new Color(255, 255, 255, 220));
        con =dbconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setMaximumSize(new java.awt.Dimension(1359, 719));
        setMinimumSize(new java.awt.Dimension(1359, 719));
        setPreferredSize(new java.awt.Dimension(1359, 719));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1359, 560));
        jPanel1.setMinimumSize(new java.awt.Dimension(1359, 560));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1359, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1359, 570));

        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jButton2.setText("send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 130, 50));

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 130, 50));

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jButton3.setText("recieved");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 170, 50));

        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jButton4.setText("sold");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 140, 50));

        jButton5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jButton5.setText("profit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 140, 50));

        jButton6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jButton6.setText("log out");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/admin1.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1359, 160));
        jLabel1.setMinimumSize(new java.awt.Dimension(1359, 160));
        jLabel1.setPreferredSize(new java.awt.Dimension(1359, 160));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1359, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        add a = new add();
        jploade.jPanelLoader(jPanel1, a);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        send s = new send();
        jploade.jPanelLoader(jPanel1, s);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         recieved r = new recieved();
        jploade.jPanelLoader(jPanel1, r);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        sold w = new sold();
        jploade.jPanelLoader(jPanel1, w);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        profit pro = new profit();
        jploade.jPanelLoader(jPanel1, pro);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null, "Do you want to pass recieved item for new stock ?"); 
       if(x==0){
           
           try{
     
         String Sql="UPDATE add1, recieved  SET add1.tot_pac = recieved.tot_pac , add1.box=recieved.r_box , add1.pac=recieved.r_packet WHERE add1.product_name = recieved.r_name ";
         String sql2="DELETE * FROM send";
        pst=con.prepareStatement(Sql);
       
          pst.execute();
        
           }catch (Exception e) {
           System.out.println();
        }
           try{
     
       stmt=con.createStatement();
         String sql2="DELETE FROM send";
       stmt.executeUpdate(sql2);
       
       
        }catch (Exception e) {
           System.out.println();
        }
           try{
     
       stmt=con.createStatement();
         String sql2="DELETE FROM recieved";
       stmt.executeUpdate(sql2);
       
       
        }catch (Exception e) {
           System.out.println();
        }
           home a = new home();
                 a.setVisible(true);
                 this.dispose();
       }
       else if(x==1) {
           
          home a = new home();
                 a.setVisible(true);
                 this.dispose();
           
           
       }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
