/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import mycode.dbconnect;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Acer
 */
public class recieved extends javax.swing.JPanel {

    /**
     * Creates new form recieved
     */
     Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    
    public recieved() {
        initComponents();
        jPanel1.setBackground(new Color(255,255,255,180));
         
        con =dbconnect.connect();
        showDate();
       theder();
        data_load();
        
        jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        jTable1.getTableHeader().setOpaque(false);
       
        jTable1.getTableHeader().setBackground(new Color(255,51,51));
        jTable1.getTableHeader().setForeground( Color.BLACK);
        jTable1.setRowHeight(25);
    }
    void showDate(){
    
    SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
    Date d = new Date();
    jLabel14.setText(s.format(d));
    }
    
     
      public void pro_tot_cal(){  
          
          int in_box=Integer.parseInt(jLabel10.getText());
          int send_box=Integer.parseInt(jTextField1.getText());
          int send_loose=Integer.parseInt(jTextField2.getText());
          
          int tot;
          tot=(in_box*send_box)+send_loose;
          jLabel6.setText(String.valueOf(tot));
          
          
          
      }
      private void theder(){
        
         JTableHeader theder = jTable1.getTableHeader();
          theder.setFont(new Font("Segoe UI",Font.BOLD,24));
      }
      public void data_load(){
        
       try{
           
          Statement s = dbconnect.connect().createStatement(); 
          ResultSet rs = s.executeQuery("SELECT * FROM add1");
          Vector v = new Vector();
          while(rs.next()){
              
            v.add(rs.getString("product_name"));
            
            DefaultComboBoxModel com = new DefaultComboBoxModel(v);
            jComboBox1.setModel(com);
              
              
          }
          
           
           
           
       } catch(Exception e){
           
       }   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1920, 840));
        setMinimumSize(new java.awt.Dimension(1920, 840));
        setPreferredSize(new java.awt.Dimension(1920, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel8.setText("0 ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 220, 25));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel10.setText("0");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 150, 25));

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 220, 30));

        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel_100824.jpg"))); // NOI18N
        jButton2.setText("remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 150, 40));

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/ok_100483.jpg"))); // NOI18N
        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 130, 40));

        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/save.png"))); // NOI18N
        jButton4.setText("save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 470, 150, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Bar Code", "No Of Recieved Boxes", "No Of Recieved Loose Packet", "Total Recieved"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 870, 440));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setText("product name        :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 25));

        jComboBox1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 270, 25));

        jTextField1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 240, 25));

        jTextField2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 240, 25));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel7.setText("id   :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 40, 25));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setText("recieved");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, 25));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setText("loose packet          :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, 25));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel9.setText("No Of pac in box    :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 170, 25));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel5.setText("recieved box          :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 25));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/date.gif"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 60, 60));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel13.setText("date  :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 750, -1, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/recieved.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 560));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/reci.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 880, 120));

        jLabel6.setText("00");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 76, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String name =jComboBox1.getSelectedItem().toString();
        try{

            Statement s =dbconnect.connect().createStatement();
            ResultSet rs = s.executeQuery("SELECT add_id,box_pac FROM add1 WHERE product_name ='"+name+"'");
            if(rs.next()){

                jLabel8.setText(rs.getString("add_id"));
                jLabel10.setText(rs.getString("box_pac"));

            }

        }catch(Exception e){

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt =(DefaultTableModel) jTable1.getModel();
        Vector v = new Vector();

        v.add(jComboBox1.getSelectedItem().toString());
        v.add(jLabel8.getText());
        v.add(jTextField1.getText());
        v.add(jTextField2.getText());
        pro_tot_cal();
        v.add(jLabel6.getText());

        dt.addRow(v);

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{

            DefaultTableModel dt =(DefaultTableModel) jTable1.getModel();
            int rw = jTable1.getSelectedRow();

            dt.removeRow(rw);

        }catch(Exception e){

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null, "That is the end of recieved for today ?"); 
       if(x==1){ 
       try{
         
       DefaultTableModel dt =(DefaultTableModel)jTable1.getModel();
       int rc = dt.getRowCount();
       
       for(int i =0;i<rc; i++){
           
           String p_name1 = dt.getValueAt(i, 0).toString();
           String inid = dt.getValueAt(i, 1).toString();
           String sendb = dt.getValueAt(i, 2).toString();
           String sendl = dt.getValueAt(i, 3).toString();
           String tot = dt.getValueAt(i, 4).toString();
          
           Statement ss =dbconnect.connect().createStatement();
           ss.executeUpdate("INSERT INTO Recieved (r_name , p_id , r_box , r_packet ,tot_pac) VALUES('"+p_name1+"' , '"+inid+"' , '"+sendb+"' , '"+sendl+"' ,  '"+tot+"')");
       }
       
          JOptionPane.showMessageDialog(null, "Data Saved");
          
          
          
          
      }catch(HeadlessException | SQLException e){
           System.out.println(e);
      } 
       
        try { 
            
           
    
      String sql="update send set tot_send=tot_send-? where p_name=? ";
        
           pst=con.prepareStatement(sql);
          
       for(int i=0;i<jTable1.getRowCount();i++){
        
           String pid = (String)jTable1.getValueAt(i, 0);
         String qty=(String)jTable1.getValueAt(i, 4);
         
             pst.setString(1, qty);
             pst.setString(2, pid);
               pst.execute();
               
       }
        } catch (Exception e) {
           
        }
        try{
        String Sql="UPDATE send SET send_box= (tot_send-send_loose)/no_box   WHERE send_id IS NOT NULL";
        
        pst=con.prepareStatement(Sql);
       
          pst.execute();
        }catch (Exception e) {
           
        }
        try{
        
        String Sql2="update send set send_loose=tot_send%no_box  where send_id is not null";
       
        pst=con.prepareStatement(Sql2);
          pst.execute();
        }catch (Exception e) {
           
        }
       }
       else if(x==0){
      
          try{
         
       DefaultTableModel dt =(DefaultTableModel)jTable1.getModel();
       int rc = dt.getRowCount();
       
       for(int i =0;i<rc; i++){
           
           String p_name1 = dt.getValueAt(i, 0).toString();
           String inid = dt.getValueAt(i, 1).toString();
           String sendb = dt.getValueAt(i, 2).toString();
           String sendl = dt.getValueAt(i, 3).toString();
           String tot = dt.getValueAt(i, 4).toString();
          
           Statement ss =dbconnect.connect().createStatement();
           ss.executeUpdate("INSERT INTO Recieved (r_name , p_id , r_box , r_packet ,tot_pac) VALUES('"+p_name1+"' , '"+inid+"' , '"+sendb+"' , '"+sendl+"' ,  '"+tot+"')");
       }
       
          JOptionPane.showMessageDialog(null, "Data Saved");
          
          
          
          
      }catch(HeadlessException | SQLException e){
           System.out.println(e);
      } 
       
        try { 
            
           
    
      String sql="update send set tot_send=tot_send-? where p_name=? ";
        
           pst=con.prepareStatement(sql);
          
       for(int i=0;i<jTable1.getRowCount();i++){
        
           String pid = (String)jTable1.getValueAt(i, 0);
         String qty=(String)jTable1.getValueAt(i, 4);
         
             pst.setString(1, qty);
             pst.setString(2, pid);
               pst.execute();
               
       }
        } catch (Exception e) {
           
        }
        
         try{
        
        String Sql2="update send set send_loose=tot_send%no_box  where send_id is not null";
       
        pst=con.prepareStatement(Sql2);
          pst.execute();
        }catch (Exception e) {
           
        } 
        try{
        String Sql="UPDATE send SET send_box= (tot_send-send_loose)/no_box   WHERE send_id IS NOT NULL";
        
        pst=con.prepareStatement(Sql);
       
          pst.execute();
        }catch (Exception e) {
           
        }  
           
           
           try{
             
           Statement s =dbconnect.connect().createStatement();
           ResultSet rs = s.executeQuery("select p_name, no_box,send_box,send_loose, tot_send ,u_price from send  ");
           
            while(rs.next()){
                
                String da= jLabel14.getText();
                String p=rs.getString("p_name");
              
                String pri=rs.getString("u_price");
                Double price=Double.parseDouble(pri);
                int i = rs.getInt("no_box");
                int sold_box1 = rs.getInt("send_box");
                int sold_loose = rs.getInt("send_loose");
                int tot_sold = rs.getInt("tot_send");
                double profit1;
                
                profit1=(price*tot_sold);
                String profit=String.format("%.2f", profit1);
                
                
                Statement sss =dbconnect.connect().createStatement();
            sss.executeUpdate("insert into sold(date,sold_name,sold_box,sold_pac,sold_tot,tot_profit) values('"+da+"' , '"+p+"', '"+sold_box1+"', '"+sold_loose+"', '"+tot_sold+"', '"+profit+"')");
            }
             
              
         }catch(Exception e){
             
         }
       } 
         
         
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
