/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import mycode.dbconnect;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Acer
 */
public class send extends javax.swing.JPanel {

    /**
     * Creates new form send
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    
    public send() {
        initComponents();
        jPanel1.setBackground(new Color(255,255,255,180));
        con =dbconnect.connect();
        theder();
        data_load();
        
        jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
        jTable1.getTableHeader().setOpaque(false);
       
        jTable1.getTableHeader().setBackground(new Color(255,51,51));
        jTable1.getTableHeader().setForeground( Color.BLACK);
        jTable1.setRowHeight(25);
    }
    
      public void pro_tot_cal(){  
          
          int in_box=Integer.parseInt(jLabel10.getText());
          int send_box=Integer.parseInt(jLabel14.getText());
          int send_loose=Integer.parseInt(jLabel13.getText());
          
          int tot;
          tot=(in_box*send_box)+send_loose;
          jLabel6.setText(String.valueOf(tot));
          
          
          
      }
      public void data_load(){
        
       try{
           
          Statement s = dbconnect.connect().createStatement(); 
          ResultSet rs = s.executeQuery("SELECT * FROM add1");
          Vector v = new Vector();
          while(rs.next()){
              
            v.add(rs.getString("product_name"));
            
            DefaultComboBoxModel com = new DefaultComboBoxModel(v);
            jComboBox1.setModel(com);
              
              
          }
          
           
           
           
       } catch(Exception e){
           
       }   }
      private void theder(){
        
         JTableHeader theder = jTable1.getTableHeader();
          theder.setFont(new Font("Segoe UI",Font.BOLD,24));
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1920, 840));
        setMinimumSize(new java.awt.Dimension(1920, 840));
        setPreferredSize(new java.awt.Dimension(1920, 840));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel10.setText("0");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 170, 25));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel13.setText("0");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 170, 25));

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel14.setText("0");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 180, 25));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel8.setText("0 ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 200, 25));

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/ok_100483.jpg"))); // NOI18N
        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 130, 40));

        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel_100824.jpg"))); // NOI18N
        jButton2.setText("delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 150, 40));

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/save.png"))); // NOI18N
        jButton3.setText("save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 470, 150, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Bar Code", "No Of Send Boxes", "No Of Send Loose Packet", "Total Send Packet", "No Of Packet In box", "Unit Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 870, 440));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setText("product name        :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 25));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setText("send box                  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 180, 25));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setText("send loose packet  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, 25));

        jComboBox1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 270, 25));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel7.setText("id  :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 30, 25));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel9.setText("No Of pac in box    :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 170, 25));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/send.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 560));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/sendd.png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 880, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setText("0");
        jLabel6.setToolTipText("");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 180, 30));

        jLabel5.setText("0");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 30));

        jLabel12.setText("0");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 160, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String name =jComboBox1.getSelectedItem().toString();
        try{
            
           Statement s =dbconnect.connect().createStatement();
           ResultSet rs = s.executeQuery("SELECT add_id,box_pac,u_price,box,pac FROM add1 WHERE product_name ='"+name+"'");
           if(rs.next()){
               
              jLabel8.setText(rs.getString("add_id"));
              jLabel10.setText(rs.getString("box_pac"));
              jLabel12.setText(rs.getString("u_price"));
              jLabel14.setText(rs.getString("box"));
              jLabel13.setText(rs.getString("pac"));
              
               
           }
           
         
            
        }catch(Exception e){
            
            
            
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt =(DefaultTableModel) jTable1.getModel();
        Vector v = new Vector();
        
        v.add(jComboBox1.getSelectedItem().toString());
        v.add(jLabel8.getText());
        v.add(jLabel14.getText());
         v.add(jLabel13.getText());
          pro_tot_cal();
        v.add(jLabel6.getText());
        v.add(jLabel10.getText());
        v.add(jLabel12.getText());
        dt.addRow(v);
    
           
    
      
    
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            
           DefaultTableModel dt =(DefaultTableModel) jTable1.getModel();
           int rw = jTable1.getSelectedRow();
           
           dt.removeRow(rw);
            
            
        }catch(Exception e){
            
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        int r = jTable1.getSelectedRow();
        String uit = jTable1.getValueAt(r, 0).toString();
       
        jLabel5.setText(uit);
          
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
         
       DefaultTableModel dt =(DefaultTableModel)jTable1.getModel();
       int rc = dt.getRowCount();
       
       for(int i =0;i<rc; i++){
           
           String p_name1 = dt.getValueAt(i, 0).toString();
           String inid = dt.getValueAt(i, 1).toString();
           String sendb = dt.getValueAt(i, 2).toString();
           String sendl = dt.getValueAt(i, 3).toString();
           String tot = dt.getValueAt(i, 4).toString();
           String noInBox = dt.getValueAt(i, 5).toString();
           String price = dt.getValueAt(i, 6).toString();
         
          
           Statement ss =dbconnect.connect().createStatement();
           ss.executeUpdate("INSERT INTO send (p_name , p_id , send_box , send_loose ,tot_send,no_box,u_price) VALUES('"+p_name1+"' , '"+inid+"' , '"+sendb+"' , '"+sendl+"' ,  '"+tot+"','"+noInBox+"','"+price+"')");
       }
       
          JOptionPane.showMessageDialog(null, "Data Saved");
          
          
          
          
      }catch(HeadlessException | SQLException e){
           System.out.println(e);
      }  
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
